name: ASV Benchmark

on:
  push:
    branches:
      - main  # Run benchmarks on every commit to the main branch
  workflow_dispatch:
    

jobs:

  benchmark:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: "kedro"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or the version you want to test

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asv  # Install ASV
          # pip install -e ".[test]"  # Your project dependencies, if needed
      - name: Run ASV benchmarks
        run: |
          cd kedro
          asv machine --yes
          asv run

      - name: Set git email and name
        run: |
          git config --global user.email "ankitakatiyar2401@gmail.com"
          git config --global user.name "ankatiyar"  
      
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ankatiyar/benchmark-kedro 
          token: ${{ secrets.ANKITA }}  
          ref: 'main'
          path: "benchmark-kedro"
      
      - name: Copy files to target repository
        run: |
          cp -r /home/runner/work/kedro/kedro/kedro/.asv /home/runner/work/kedro/kedro/benchmark-kedro/

      - name: Commit and Push changes
        run: |
          cd benchmark-kedro
          git add .
          git commit -m "Add files from source repository"
          git push
