name: Label PRs
on:
  pull_request_target:
    types:
      - opened
      - synchronize


jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5