name: Sync `main` and `develop`

on:
  schedule:
    - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set git email and name
        run: |
          git config --global user.email "ankitakatiyar2401@gmail.com"
          git config --global user.name "ankatiyar"

      - name: maybe merge upstream into master or raise a PR
        run: ./tools/github_actions/merge.sh . "main" "develop" "${{ secrets.GITHUB_TOKEN }}"
