name: Trigger Release

on:
  release:
    types: [created]
permissions:
  contents: write
  
jobs:
  trigger-release:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Release in Target Repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.NEW }}  # Personal Access Token or Repo Token with appropriate permissions
          repository: ankatiyar/kedro-starters
          event-type: release-triggered
