name: Trigger Starter Release

on:
  release:
    types: [published]
  
jobs:
  trigger-release:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger release in kedro-starters
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}  # Personal Access Token or Repo Token with appropriate permissions
          repository: ankatiyar/kedro-starters
          event-type: release-triggered
